import unittest
from gfsad.utils import find_country


class TestCountries(unittest.TestCase):
    countries = [{'lat': '33', 'lng': '65', 'id': '004', 'continent': 'Asia', 'name': 'Afghanistan'},
                 {'lat': '41', 'lng': '20', 'id': '008', 'continent': 'Europe', 'name': 'Albania'},
                 {'lat': '28', 'lng': '3', 'id': '012', 'continent': 'Africa', 'name': 'Algeria'},
                 {'lat': '43.7333', 'lng': '7.4', 'id': '250', 'continent': 'Europe', 'name': 'France'},
                 {'lat': '-12.5', 'lng': '18.5', 'id': '024', 'continent': 'Africa', 'name': 'Angola'},
                 {'lat': '-34', 'lng': '-64', 'id': '032', 'continent': 'South America', 'name': 'Argentina'},
                 {'lat': '40', 'lng': '45', 'id': '051', 'continent': 'Asia', 'name': 'Armenia'},
                 {'lat': '-27', 'lng': '133', 'id': '036', 'continent': 'Oceania', 'name': 'Australia'},
                 {'lat': '47.1667', 'lng': '9.5333', 'id': '040', 'continent': 'Europe', 'name': 'Austria'},
                 {'lat': '40.5', 'lng': '47.5', 'id': '031', 'continent': 'Asia', 'name': 'Azerbaijan'},
                 {'lat': '24', 'lng': '90', 'id': '050', 'continent': 'Asia', 'name': 'Bangladesh'},
                 {'lat': '53', 'lng': '28', 'id': '112', 'continent': 'Europe', 'name': 'Belarus'},
                 {'lat': '50.8333', 'lng': '4', 'id': '056', 'continent': 'Europe', 'name': 'Belgium'},
                 {'lat': '17.25', 'lng': '-88.75', 'id': '084', 'continent': 'North America', 'name': 'Belize'},
                 {'lat': '9.5', 'lng': '2.25', 'id': '204', 'continent': 'Africa', 'name': 'Benin'},
                 {'lat': '27.5', 'lng': '90.5', 'id': '064', 'continent': 'Asia', 'name': 'Bhutan'},
                 {'lat': '-17', 'lng': '-65', 'id': '068', 'continent': 'South America', 'name': 'Bolivia'},
                 {'lat': '44', 'lng': '18', 'id': '070', 'continent': 'Europe', 'name': 'Bosnia and Herz.'},
                 {'lat': '-22', 'lng': '24', 'id': '072', 'continent': 'Africa', 'name': 'Botswana'},
                 {'lat': '-10', 'lng': '-55', 'id': '076', 'continent': 'South America', 'name': 'Brazil'},
                 {'lat': '4.5', 'lng': '114.6667', 'id': '096', 'continent': 'Asia', 'name': 'Brunei'},
                 {'lat': '43', 'lng': '25', 'id': '100', 'continent': 'Europe', 'name': 'Bulgaria'},
                 {'lat': '13', 'lng': '-2', 'id': '854', 'continent': 'Africa', 'name': 'Burkina Faso'},
                 {'lat': '-3.5', 'lng': '30', 'id': '108', 'continent': 'Africa', 'name': 'Burundi'},
                 {'lat': '13', 'lng': '105', 'id': '116', 'continent': 'Asia', 'name': 'Cambodia'},
                 {'lat': '6', 'lng': '12', 'id': '120', 'continent': 'Africa', 'name': 'Cameroon'},
                 {'lat': '60', 'lng': '-95', 'id': '124', 'continent': 'North America', 'name': 'Canada'},
                 {'lat': '7', 'lng': '21', 'id': '140', 'continent': 'Africa', 'name': 'Central African Rep.'},
                 {'lat': '15', 'lng': '19', 'id': '148', 'continent': 'Africa', 'name': 'Chad'},
                 {'lat': '-30', 'lng': '-71', 'id': '152', 'continent': 'South America', 'name': 'Chile'},
                 {'lat': '22.25', 'lng': '114.1667', 'id': '156', 'continent': 'Asia', 'name': 'China'},
                 {'lat': '4', 'lng': '-72', 'id': '170', 'continent': 'South America', 'name': 'Colombia'},
                 {'lat': '-1', 'lng': '15', 'id': '178', 'continent': 'Africa', 'name': 'Congo'},
                 {'lat': '0', 'lng': '25', 'id': '180', 'continent': 'Africa', 'name': 'Dem. Rep. Congo'},
                 {'lat': '10', 'lng': '-84', 'id': '188', 'continent': 'North America', 'name': 'Costa Rica'},
                 {'lat': '8', 'lng': '-5', 'id': '384', 'continent': 'Africa', 'name': ''},
                 {'lat': '45.1667', 'lng': '15.5', 'id': '191', 'continent': 'Europe', 'name': 'Croatia'},
                 {'lat': '35', 'lng': '33', 'id': '196', 'continent': 'Asia', 'name': 'Cyprus'},
                 {'lat': '49.75', 'lng': '15.5', 'id': '203', 'continent': 'Europe', 'name': 'Czech Rep.'},
                 {'lat': '56', 'lng': '10', 'id': '208', 'continent': 'Europe', 'name': 'Denmark'},
                 {'lat': '11.5', 'lng': '43', 'id': '262', 'continent': 'Africa', 'name': 'Djibouti'},
                 {'lat': '19', 'lng': '-70.6667', 'id': '214', 'continent': 'North America', 'name': 'Dominican Rep.'},
                 {'lat': '-2', 'lng': '-77.5', 'id': '218', 'continent': 'South America', 'name': 'Ecuador'},
                 {'lat': '27', 'lng': '30', 'id': '818', 'continent': 'Africa', 'name': 'Egypt'},
                 {'lat': '13.8333', 'lng': '-88.9167', 'id': '222', 'continent': 'North America',
                  'name': 'El Salvador'},
                 {'lat': '2', 'lng': '10', 'id': '226', 'continent': 'Africa', 'name': 'Eq. Guinea'},
                 {'lat': '15', 'lng': '39', 'id': '232', 'continent': 'Africa', 'name': 'Eritrea'},
                 {'lat': '59', 'lng': '26', 'id': '233', 'continent': 'Europe', 'name': 'Estonia'},
                 {'lat': '8', 'lng': '38', 'id': '231', 'continent': 'Africa', 'name': 'Ethiopia'},
                 {'lat': '-51.75', 'lng': '-59', 'id': '238', 'continent': 'South America', 'name': 'Falkland Is.'},
                 {'lat': '64', 'lng': '26', 'id': '246', 'continent': 'Europe', 'name': 'Finland'},
                 {'lat': '43.7333', 'lng': '7.4', 'id': '250', 'continent': 'Europe', 'name': 'France'},
                 {'lat': '43.7333', 'lng': '7.4', 'id': '250', 'continent': 'Europe', 'name': 'France'},
                 {'lat': '-1', 'lng': '11.75', 'id': '266', 'continent': 'Africa', 'name': 'Gabon'},
                 {'lat': '13.4667', 'lng': '-16.5667', 'id': '270', 'continent': 'Africa', 'name': 'Gambia'},
                 {'lat': '42', 'lng': '43.5', 'id': '268', 'continent': 'Asia', 'name': 'Georgia'},
                 {'lat': '51', 'lng': '9', 'id': '276', 'continent': 'Europe', 'name': 'Germany'},
                 {'lat': '8', 'lng': '-2', 'id': '288', 'continent': 'Africa', 'name': 'Ghana'},
                 {'lat': '40', 'lng': '-4', 'id': '724', 'continent': 'Europe', 'name': 'Spain'},
                 {'lat': '39', 'lng': '22', 'id': '300', 'continent': 'Europe', 'name': 'Greece'},
                 {'lat': '72', 'lng': '-40', 'id': '304', 'continent': 'North America', 'name': 'Greenland'},
                 {'lat': '15.5', 'lng': '-90.25', 'id': '320', 'continent': 'North America', 'name': 'Guatemala'},
                 {'lat': '11', 'lng': '-10', 'id': '324', 'continent': 'Africa', 'name': 'Guinea'},
                 {'lat': '12', 'lng': '-15', 'id': '624', 'continent': 'Africa', 'name': 'Guinea-Bissau'},
                 {'lat': '5', 'lng': '-59', 'id': '328', 'continent': 'South America', 'name': 'Guyana'},
                 {'lat': '19', 'lng': '-72.4167', 'id': '332', 'continent': 'North America', 'name': 'Haiti'},
                 {'lat': '43.7667', 'lng': '12.4167', 'id': '380', 'continent': 'Europe', 'name': 'Italy'},
                 {'lat': '15', 'lng': '-86.5', 'id': '340', 'continent': 'North America', 'name': 'Honduras'},
                 {'lat': '22.25', 'lng': '114.1667', 'id': '156', 'continent': 'Asia', 'name': 'China'},
                 {'lat': '47', 'lng': '20', 'id': '348', 'continent': 'Europe', 'name': 'Hungary'},
                 {'lat': '65', 'lng': '-18', 'id': '352', 'continent': 'Europe', 'name': 'Iceland'},
                 {'lat': '20', 'lng': '77', 'id': '356', 'continent': 'Asia', 'name': 'India'},
                 {'lat': '-5', 'lng': '120', 'id': '360', 'continent': 'Asia', 'name': 'Indonesia'},
                 {'lat': '32', 'lng': '53', 'id': '364', 'continent': 'Asia', 'name': 'Iran'},
                 {'lat': '33', 'lng': '44', 'id': '368', 'continent': 'Asia', 'name': 'Iraq'},
                 {'lat': '53', 'lng': '-8', 'id': '372', 'continent': 'Europe', 'name': 'Ireland'},
                 {'lat': '31.5', 'lng': '34.75', 'id': '376', 'continent': 'Asia', 'name': 'Israel'},
                 {'lat': '43.7667', 'lng': '12.4167', 'id': '380', 'continent': 'Europe', 'name': 'Italy'},
                 {'lat': '18.25', 'lng': '-77.5', 'id': '388', 'continent': 'North America', 'name': 'Jamaica'},
                 {'lat': '36', 'lng': '138', 'id': '392', 'continent': 'Asia', 'name': 'Japan'},
                 {'lat': '31', 'lng': '36', 'id': '400', 'continent': 'Asia', 'name': 'Jordan'},
                 {'lat': '48', 'lng': '68', 'id': '398', 'continent': 'Asia', 'name': 'Kazakhstan'},
                 {'lat': '1', 'lng': '38', 'id': '404', 'continent': 'Africa', 'name': 'Kenya'},
                 {'lat': '40', 'lng': '127', 'id': '408', 'continent': 'Asia', 'name': 'Dem. Rep. Korea'},
                 {'lat': '37', 'lng': '127.5', 'id': '410', 'continent': 'Asia', 'name': 'Korea'},
                 {'lat': '29.3375', 'lng': '47.6581', 'id': '414', 'continent': 'Asia', 'name': 'Kuwait'},
                 {'lat': '41', 'lng': '75', 'id': '417', 'continent': 'Asia', 'name': 'Kyrgyzstan'},
                 {'lat': '16', 'lng': '106', 'id': '418', 'continent': 'Asia', 'name': 'Lao PDR'},
                 {'lat': '57', 'lng': '25', 'id': '428', 'continent': 'Europe', 'name': 'Latvia'},
                 {'lat': '33.8333', 'lng': '35.8333', 'id': '422', 'continent': 'Asia', 'name': 'Lebanon'},
                 {'lat': '-29.5', 'lng': '28.5', 'id': '426', 'continent': 'Africa', 'name': 'Lesotho'},
                 {'lat': '6.5', 'lng': '-9.5', 'id': '430', 'continent': 'Africa', 'name': 'Liberia'},
                 {'lat': '25', 'lng': '17', 'id': '434', 'continent': 'Africa', 'name': 'Libya'},
                 {'lat': '47.1667', 'lng': '9.5333', 'id': '040', 'continent': 'Europe', 'name': 'Austria'},
                 {'lat': '56', 'lng': '24', 'id': '440', 'continent': 'Europe', 'name': 'Lithuania'},
                 {'lat': '49.75', 'lng': '6.1667', 'id': '442', 'continent': 'Europe', 'name': 'Luxembourg'},
                 {'lat': '41.8333', 'lng': '22', 'id': '807', 'continent': 'Europe', 'name': 'Macedonia'},
                 {'lat': '-20', 'lng': '47', 'id': '450', 'continent': 'Africa', 'name': 'Madagascar'},
                 {'lat': '-13.5', 'lng': '34', 'id': '454', 'continent': 'Africa', 'name': 'Malawi'},
                 {'lat': '1.3667', 'lng': '103.8', 'id': '458', 'continent': 'Asia', 'name': 'Malaysia'},
                 {'lat': '17', 'lng': '-4', 'id': '466', 'continent': 'Africa', 'name': 'Mali'},
                 {'lat': '20', 'lng': '-12', 'id': '478', 'continent': 'Africa', 'name': 'Mauritania'},
                 {'lat': '23', 'lng': '-102', 'id': '484', 'continent': 'North America', 'name': 'Mexico'},
                 {'lat': '47', 'lng': '29', 'id': '498', 'continent': 'Europe', 'name': 'Moldova'},
                 {'lat': '43.7333', 'lng': '7.4', 'id': '250', 'continent': 'Europe', 'name': 'France'},
                 {'lat': '46', 'lng': '105', 'id': '496', 'continent': 'Asia', 'name': 'Mongolia'},
                 {'lat': '24.5', 'lng': '-13', 'id': '504', 'continent': 'Africa', 'name': 'Morocco'},
                 {'lat': '-18.25', 'lng': '35', 'id': '508', 'continent': 'Africa', 'name': 'Mozambique'},
                 {'lat': '22', 'lng': '98', 'id': '104', 'continent': 'Asia', 'name': 'Myanmar'},
                 {'lat': '-22', 'lng': '17', 'id': '516', 'continent': 'Africa', 'name': 'Namibia'},
                 {'lat': '28', 'lng': '84', 'id': '524', 'continent': 'Asia', 'name': 'Nepal'},
                 {'lat': '52.5', 'lng': '5.75', 'id': '528', 'continent': 'Europe', 'name': 'Netherlands'},
                 {'lat': '-21.5', 'lng': '165.5', 'id': '540', 'continent': 'Oceania', 'name': 'New Caledonia'},
                 {'lat': '-41', 'lng': '174', 'id': '554', 'continent': 'Oceania', 'name': 'New Zealand'},
                 {'lat': '13', 'lng': '-85', 'id': '558', 'continent': 'North America', 'name': 'Nicaragua'},
                 {'lat': '16', 'lng': '8', 'id': '562', 'continent': 'Africa', 'name': 'Niger'},
                 {'lat': '10', 'lng': '8', 'id': '566', 'continent': 'Africa', 'name': 'Nigeria'},
                 {'lat': '62', 'lng': '10', 'id': '578', 'continent': 'Europe', 'name': 'Norway'},
                 {'lat': '21', 'lng': '57', 'id': '512', 'continent': 'Asia', 'name': 'Oman'},
                 {'lat': '30', 'lng': '70', 'id': '586', 'continent': 'Asia', 'name': 'Pakistan'},
                 {'lat': '32', 'lng': '35.25', 'id': '275', 'continent': 'Asia', 'name': 'Palestine'},
                 {'lat': '9', 'lng': '-80', 'id': '591', 'continent': 'North America', 'name': 'Panama'},
                 {'lat': '-6', 'lng': '147', 'id': '598', 'continent': 'Oceania', 'name': 'Papua New Guinea'},
                 {'lat': '-23', 'lng': '-58', 'id': '600', 'continent': 'South America', 'name': 'Paraguay'},
                 {'lat': '-10', 'lng': '-76', 'id': '604', 'continent': 'South America', 'name': 'Peru'},
                 {'lat': '52', 'lng': '20', 'id': '616', 'continent': 'Europe', 'name': 'Poland'},
                 {'lat': '39.5', 'lng': '-8', 'id': '620', 'continent': 'Europe', 'name': 'Portugal'},
                 {'lat': '18.25', 'lng': '-66.5', 'id': '630', 'continent': 'North America', 'name': 'Puerto Rico'},
                 {'lat': '25.5', 'lng': '51.25', 'id': '634', 'continent': 'Asia', 'name': 'Qatar'},
                 {'lat': '46', 'lng': '25', 'id': '642', 'continent': 'Europe', 'name': 'Romania'},
                 {'lat': '60', 'lng': '100', 'id': '643', 'continent': 'Europe', 'name': 'Russia'},
                 {'lat': '-2', 'lng': '30', 'id': '646', 'continent': 'Africa', 'name': 'Rwanda'},
                 {'lat': '43.7667', 'lng': '12.4167', 'id': '380', 'continent': 'Europe', 'name': 'Italy'},
                 {'lat': '25', 'lng': '45', 'id': '682', 'continent': 'Asia', 'name': 'Saudi Arabia'},
                 {'lat': '14', 'lng': '-14', 'id': '686', 'continent': 'Africa', 'name': 'Senegal'},
                 {'lat': '44', 'lng': '21', 'id': '688', 'continent': 'Europe', 'name': 'Serbia'},
                 {'lat': '8.5', 'lng': '-11.5', 'id': '694', 'continent': 'Africa', 'name': 'Sierra Leone'},
                 {'lat': '1.3667', 'lng': '103.8', 'id': '458', 'continent': 'Asia', 'name': 'Malaysia'},
                 {'lat': '48.6667', 'lng': '19.5', 'id': '703', 'continent': 'Europe', 'name': 'Slovakia'},
                 {'lat': '46', 'lng': '15', 'id': '705', 'continent': 'Europe', 'name': 'Slovenia'},
                 {'lat': '-8', 'lng': '159', 'id': '090', 'continent': 'Oceania', 'name': 'Solomon Is.'},
                 {'lat': '10', 'lng': '49', 'id': '706', 'continent': 'Africa', 'name': 'Somalia'},
                 {'lat': '-29', 'lng': '24', 'id': '710', 'continent': 'Africa', 'name': 'South Africa'},
                 {'lat': '40', 'lng': '-4', 'id': '724', 'continent': 'Europe', 'name': 'Spain'},
                 {'lat': '7', 'lng': '81', 'id': '144', 'continent': 'Asia', 'name': 'Sri Lanka'},
                 {'lat': '15', 'lng': '30', 'id': '729', 'continent': 'Africa', 'name': 'Sudan'},
                 {'lat': '4', 'lng': '-56', 'id': '740', 'continent': 'South America', 'name': 'Suriname'},
                 {'lat': '-26.5', 'lng': '31.5', 'id': '748', 'continent': 'Africa', 'name': 'Swaziland'},
                 {'lat': '62', 'lng': '15', 'id': '752', 'continent': 'Europe', 'name': 'Sweden'},
                 {'lat': '47', 'lng': '8', 'id': '756', 'continent': 'Europe', 'name': 'Switzerland'},
                 {'lat': '35', 'lng': '38', 'id': '760', 'continent': 'Asia', 'name': 'Syria'},
                 {'lat': '23.5', 'lng': '121', 'id': '158', 'continent': 'Asia', 'name': 'Taiwan'},
                 {'lat': '39', 'lng': '71', 'id': '762', 'continent': 'Asia', 'name': 'Tajikistan'},
                 {'lat': '-6', 'lng': '35', 'id': '834', 'continent': 'Africa', 'name': 'Tanzania'},
                 {'lat': '15', 'lng': '100', 'id': '764', 'continent': 'Asia', 'name': 'Thailand'},
                 {'lat': '-8.55', 'lng': '125.5167', 'id': '626', 'continent': 'Asia', 'name': 'Timor-Leste'},
                 {'lat': '8', 'lng': '1.1667', 'id': '768', 'continent': 'Africa', 'name': 'Togo'},
                 {'lat': '34', 'lng': '9', 'id': '788', 'continent': 'Africa', 'name': 'Tunisia'},
                 {'lat': '39', 'lng': '35', 'id': '792', 'continent': 'Asia', 'name': 'Turkey'},
                 {'lat': '40', 'lng': '60', 'id': '795', 'continent': 'Asia', 'name': 'Turkmenistan'},
                 {'lat': '1', 'lng': '32', 'id': '800', 'continent': 'Africa', 'name': 'Uganda'},
                 {'lat': '49', 'lng': '32', 'id': '804', 'continent': 'Europe', 'name': 'Ukraine'},
                 {'lat': '24', 'lng': '54', 'id': '784', 'continent': 'Asia', 'name': 'United Arab Emirates'},
                 {'lat': '54', 'lng': '-2', 'id': '826', 'continent': 'Europe', 'name': 'United Kingdom'},
                 {'lat': '38', 'lng': '-97', 'id': '840', 'continent': 'North America', 'name': 'United States'},
                 {'lat': '-33', 'lng': '-56', 'id': '858', 'continent': 'South America', 'name': 'Uruguay'},
                 {'lat': '41', 'lng': '64', 'id': '860', 'continent': 'Asia', 'name': 'Uzbekistan'},
                 {'lat': '8', 'lng': '-66', 'id': '862', 'continent': 'South America', 'name': 'Venezuela'},
                 {'lat': '16', 'lng': '106', 'id': '418', 'continent': 'Asia', 'name': 'Lao PDR'},
                 {'lat': '24.5', 'lng': '-13', 'id': '504', 'continent': 'Africa', 'name': 'Morocco'},
                 {'lat': '15', 'lng': '48', 'id': '887', 'continent': 'Asia', 'name': 'Yemen'},
                 {'lat': '-15', 'lng': '30', 'id': '894', 'continent': 'Africa', 'name': 'Zambia'},
                 {'lat': '-20', 'lng': '30', 'id': '716', 'continent': 'Africa', 'name': 'Zimbabwe'}]


    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_countries(self):
        for country in TestCountries.countries:
            c = find_country(country['lng'], country['lat'])
            self.assertEqual(c['name'], country['name'])