"""empty message

Revision ID: 11e2f92210d1
Revises: 55c56133047a
Create Date: 2015-03-25 12:57:40.365290

"""

# revision identifiers, used by Alembic.
revision = '11e2f92210d1'
down_revision = '55c56133047a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('heading', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point', 'heading')
    ### end Alembic commands ###
