"""empty message

Revision ID: 12ec6f6ad6d1
Revises: 3def44fdeb4d
Create Date: 2015-07-22 01:05:28.612638

"""

# revision identifiers, used by Alembic.
revision = '12ec6f6ad6d1'
down_revision = '3def44fdeb4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('location', sa.Column('use_invalid', sa.Boolean(), nullable=True))
    op.add_column('location', sa.Column('use_invalid_reason', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'use_invalid_reason')
    op.drop_column('location', 'use_invalid')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    # )
    ### end Alembic commands ###
