"""empty message

Revision ID: 16fae0aff28c
Revises: 35cb866de3c8
Create Date: 2015-02-12 08:57:41.491113

"""

# revision identifiers, used by Alembic.
revision = '16fae0aff28c'
down_revision = '35cb866de3c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
