"""empty message

Revision ID: 22632e7a37d2
Revises: 57eb6804d74
Create Date: 2015-07-18 23:37:54.621168

"""

# revision identifiers, used by Alembic.
revision = '22632e7a37d2'
down_revision = '57eb6804d74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('use_private', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_location_lat'), 'location', ['lat'], unique=False)
    op.create_index(op.f('ix_location_lon'), 'location', ['lon'], unique=False)
    op.create_index(op.f('ix_location_use_private'), 'location', ['use_private'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_use_private'), table_name='location')
    op.drop_index(op.f('ix_location_lon'), table_name='location')
    op.drop_index(op.f('ix_location_lat'), table_name='location')
    op.drop_column('location', 'use_private')
    ### end Alembic commands ###
