"""empty message

Revision ID: 27bee3164fee
Revises: f7e8ea37c63
Create Date: 2015-02-08 22:15:41.472976

"""

# revision identifiers, used by Alembic.
revision = '27bee3164fee'
down_revision = 'f7e8ea37c63'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('date_edited', sa.DateTime(), nullable=True),
    sa.Column('data', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_history_record_id'), 'record_history', ['record_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_history_record_id'), table_name='record_history')
    op.drop_table('record_history')
    ### end Alembic commands ###
