"""empty message

Revision ID: 29a55bf8c8a9
Revises: 8b1d15e5ab4
Create Date: 2015-04-16 07:10:36.945310

"""

# revision identifiers, used by Alembic.
revision = '29a55bf8c8a9'
down_revision = '8b1d15e5ab4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tile_center_lat'), 'tile', ['center_lat'], unique=False)
    op.create_index(op.f('ix_tile_center_lon'), 'tile', ['center_lon'], unique=False)
    op.create_index(op.f('ix_tile_classifications_count'), 'tile', ['classifications_count'], unique=False)
    op.create_index(op.f('ix_tile_classifications_majority_agreement'), 'tile', ['classifications_majority_agreement'], unique=False)
    op.create_index(op.f('ix_tile_classifications_majority_class'), 'tile', ['classifications_majority_class'], unique=False)
    op.create_index(op.f('ix_tile_date_acquired'), 'tile', ['date_acquired'], unique=False)
    op.create_index(op.f('ix_tile_product_type'), 'tile', ['product_type'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tile_product_type'), table_name='tile')
    op.drop_index(op.f('ix_tile_date_acquired'), table_name='tile')
    op.drop_index(op.f('ix_tile_classifications_majority_class'), table_name='tile')
    op.drop_index(op.f('ix_tile_classifications_majority_agreement'), table_name='tile')
    op.drop_index(op.f('ix_tile_classifications_count'), table_name='tile')
    op.drop_index(op.f('ix_tile_center_lon'), table_name='tile')
    op.drop_index(op.f('ix_tile_center_lat'), table_name='tile')
    ### end Alembic commands ###
