"""empty message

Revision ID: 30fdcf6f95c1
Revises: 11e2f92210d1
Create Date: 2015-03-25 13:33:53.050641

"""

# revision identifiers, used by Alembic.
revision = '30fdcf6f95c1'
down_revision = '11e2f92210d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('altitude', sa.Float(), nullable=True))
    op.add_column('point', sa.Column('speed', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point', 'speed')
    op.drop_column('point', 'altitude')
    ### end Alembic commands ###
