"""empty message

Revision ID: 39b95dbe603
Revises: 24d86a6b9a4c
Create Date: 2015-03-17 14:07:54.020217

"""

# revision identifiers, used by Alembic.
revision = '39b95dbe603'
down_revision = '24d86a6b9a4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('bearing', sa.Float(), nullable=True))
    op.add_column('location', sa.Column('distance', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'distance')
    op.drop_column('location', 'bearing')
    ### end Alembic commands ###
