"""empty message

Revision ID: 3def44fdeb4d
Revises: 22632e7a37d2
Create Date: 2015-07-19 14:32:36.096493

"""

# revision identifiers, used by Alembic.
revision = '3def44fdeb4d'
down_revision = '22632e7a37d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('use_validation', sa.Boolean(), nullable=True))
    op.add_column('location', sa.Column('use_validation_locked', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_location_use_validation'), 'location', ['use_validation'], unique=False)
    op.create_index(op.f('ix_location_use_validation_locked'), 'location', ['use_validation_locked'], unique=False)
    op.drop_index('ix_location_use_valid', table_name='location')
    op.drop_index('ix_location_use_verification', table_name='location')
    op.drop_index('ix_location_use_verification_locked', table_name='location')
    op.drop_column('location', 'use_valid')
    op.drop_column('location', 'use_verification_locked')
    op.drop_column('location', 'use_verification')
    op.alter_column('record_rating', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_record_rating_user_id'), 'record_rating', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_rating_user_id'), table_name='record_rating')
    op.alter_column('record_rating', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('location', sa.Column('use_verification', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('use_verification_locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('use_valid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_location_use_verification_locked', 'location', ['use_verification_locked'], unique=False)
    op.create_index('ix_location_use_verification', 'location', ['use_verification'], unique=False)
    op.create_index('ix_location_use_valid', 'location', ['use_valid'], unique=False)
    op.drop_index(op.f('ix_location_use_validation_locked'), table_name='location')
    op.drop_index(op.f('ix_location_use_validation'), table_name='location')
    op.drop_column('location', 'use_validation_locked')
    op.drop_column('location', 'use_validation')
    ### end Alembic commands ###
