"""empty message

Revision ID: 3df3378fa9b0
Revises: 45f66908a95b
Create Date: 2015-04-10 16:04:32.131733

"""

# revision identifiers, used by Alembic.
revision = '3df3378fa9b0'
down_revision = '45f66908a95b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('ndvi_modis', postgresql.ARRAY(sa.Integer()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'ndvi_modis')
    ### end Alembic commands ###
