"""empty message

Revision ID: 43326aa692eb
Revises: 50599d90ba7
Create Date: 2015-04-16 16:47:58.001308

"""

# revision identifiers, used by Alembic.
revision = '43326aa692eb'
down_revision = '50599d90ba7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_location_use_valid'), 'location', ['use_valid'], unique=False)
    op.create_index(op.f('ix_location_use_verification'), 'location', ['use_verification'], unique=False)
    op.create_index(op.f('ix_location_use_verification_locked'), 'location', ['use_verification_locked'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_use_verification_locked'), table_name='location')
    op.drop_index(op.f('ix_location_use_verification'), table_name='location')
    op.drop_index(op.f('ix_location_use_valid'), table_name='location')
    ### end Alembic commands ###
