"""empty message

Revision ID: 45f66908a95b
Revises: 566dd697364b
Create Date: 2015-03-30 14:15:36.617100

"""

# revision identifiers, used by Alembic.
revision = '45f66908a95b'
down_revision = '566dd697364b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('request_url', sa.String(), nullable=True),
    sa.Column('request_method', sa.String(), nullable=True),
    sa.Column('request_data', sa.String(), nullable=True),
    sa.Column('response_data', sa.String(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    ### end Alembic commands ###
