"""empty message

Revision ID: 46fcf571dd27
Revises: d97e4cb6859
Create Date: 2015-02-11 08:32:35.320663

"""

# revision identifiers, used by Alembic.
revision = '46fcf571dd27'
down_revision = 'd97e4cb6859'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
