"""empty message

Revision ID: 4986e64643f4
Revises: 175003d01257
Create Date: 2015-04-15 12:16:41.965765

"""

# revision identifiers, used by Alembic.
revision = '4986e64643f4'
down_revision = '175003d01257'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tile', sa.Column('feature_id', sa.String(), nullable=False))
    op.alter_column('tile', 'date_acquired',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'tile', ['feature_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tile', type_='unique')
    op.alter_column('tile', 'date_acquired',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('tile', 'feature_id')
    ### end Alembic commands ###
