"""empty message

Revision ID: 54a207900d7a
Revises: 52168e17460f
Create Date: 2015-02-12 11:59:00.772454

"""

# revision identifiers, used by Alembic.
revision = '54a207900d7a'
down_revision = '52168e17460f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login')
    ### end Alembic commands ###
