"""empty message

Revision ID: 55c56133047a
Revises: 39b95dbe603
Create Date: 2015-03-25 12:53:41.978290

"""

# revision identifiers, used by Alembic.
revision = '55c56133047a'
down_revision = '39b95dbe603'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('date_taken', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_location_id'), 'point', ['location_id'], unique=False)
    op.add_column(u'location', sa.Column('accuracy', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'location', 'accuracy')
    op.drop_index(op.f('ix_point_location_id'), table_name='point')
    op.drop_table('point')
    ### end Alembic commands ###
