"""empty message

Revision ID: 566dd697364b
Revises: 30fdcf6f95c1
Create Date: 2015-03-25 13:39:40.598262

"""

# revision identifiers, used by Alembic.
revision = '566dd697364b'
down_revision = '30fdcf6f95c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('altitude_accuracy', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point', 'altitude_accuracy')
    ### end Alembic commands ###
