"""empty message

Revision ID: 8b1d15e5ab4
Revises: 3788c538b024
Create Date: 2015-04-16 06:53:54.516082

"""

# revision identifiers, used by Alembic.
revision = '8b1d15e5ab4'
down_revision = '3788c538b024'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
