"""empty message

Revision ID: a44d7cf0ded
Revises: 3df3378fa9b0
Create Date: 2015-04-15 11:52:19.943207

"""

# revision identifiers, used by Alembic.
revision = 'a44d7cf0ded'
down_revision = '3df3378fa9b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lon', sa.Float(), nullable=False),
    sa.Column('corner_ne_lat', sa.Float(), nullable=True),
    sa.Column('corner_ne_lon', sa.Float(), nullable=True),
    sa.Column('corner_sw_lat', sa.Float(), nullable=True),
    sa.Column('corner_sw_lon', sa.Float(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('copyright', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tile')
    ### end Alembic commands ###
