"""empty message

Revision ID: d97e4cb6859
Revises: 27bee3164fee
Create Date: 2015-02-09 23:12:53.536193

"""

# revision identifiers, used by Alembic.
revision = 'd97e4cb6859'
down_revision = '27bee3164fee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('date_rated', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('stale', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'record_id', name='one_rating_per_record_per_user')
    )
    op.create_index(op.f('ix_record_rating_record_id'), 'record_rating', ['record_id'], unique=False)
    op.add_column(u'photo', sa.Column('flagged', sa.Integer(), nullable=True))
    op.add_column(u'photo', sa.Column('source', sa.String(), nullable=True))
    op.add_column(u'record', sa.Column('protected', sa.Boolean(), nullable=True))
    op.add_column(u'record', sa.Column('validation', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'record', 'validation')
    op.drop_column(u'record', 'protected')
    op.drop_column(u'photo', 'source')
    op.drop_column(u'photo', 'flagged')
    op.drop_index(op.f('ix_record_rating_record_id'), table_name='record_rating')
    op.drop_table('record_rating')
    ### end Alembic commands ###
